service: wyatt

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-finch
  - serverless-plugin-chrome

custom:
  bucketName: ${self:service}-bills

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "*"
  environment:
    S3_BUCKET_NAME: ${self:custom.bucketName}

package:
  artifact: /tmp/workspace/build/distributions/${self:service}.zip

functions:
  wyatt-handler:
    handler: com.merricklabs.wyatt.handlers.WyattHandler
    events:
      # 5th day of every month
      - schedule: cron(0 0 5 * ? *)

resources:
  Resources:
    s3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: BucketOwnerRead