service: wyatt

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20

package:
  artifact: build/libs/${self:service}.jar

functions:
  helloworld-handler:
    handler: com.merricklabs.wyatt.handlers.WyattHandler
    events:
      # 5th day of every month
      - schedule: cron(0 0 5 * ? *)