service: wyatt

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${self:service}

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, "dev"}
  region: us-west-2
  memorySize: 512
  timeout: 20
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "*"

package:
  artifact: build/libs/${self:service}.jar

functions:
  wyatt-handler:
    handler: com.merricklabs.wyatt.handlers.WyattHandler
    events:
      # 5th day of every month
      - schedule: cron(0 0 5 * ? *)

resources:
  Resources:
    s3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.client.bucketName}
        AccessControl: BucketOwnerRead